const MEDIA_TYPE_CODES = Object.freeze({
    USER_AVATAR: "USER_AVATAR",
    ANNOUNCEMENT_IMAGE: "ANNOUNCEMENT_IMAGE",
    ANNOUNCEMENT_VIDEO: "ANNOUNCEMENT_VIDEO",
});

export default MEDIA_TYPE_CODES;
