export const ROLES = Object.freeze({
    ADMIN: "ROLE_ADMIN",
    USER: "ROLE_USER",
    ROOT: "ROLE_ROOT",
    TENANT: "ROLE_TENANT",
    OWNER: "ROLE_OWNER",
    AGENCY: "ROLE_AGENCY",
})

export const ROLE_IDS = Object.freeze({
    USER: 1,
    ADMIN: 2,
    ROOT: 3,
    TENANT: 4,
    OWNER: 5,
    AGENCY: 6,
})

export const ROLE_NAMES = Object.freeze({
    [ROLE_IDS.USER]: ROLES.USER,
    [ROLE_IDS.ADMIN]: ROLES.ADMIN,
    [ROLE_IDS.ROOT]: ROLES.ROOT,
    [ROLE_IDS.TENANT]: ROLES.TENANT,
    [ROLE_IDS.OWNER]: ROLES.OWNER,
    [ROLE_IDS.AGENCY]: ROLES.AGENCY,
})

export const AUDIT_ACTIONS = Object.freeze({
    ROLE_CHANGE: "ROLE_CHANGE",
    STATUS_CHANGE: "STATUS_CHANGE",
    PASSWORD_RESET: "PASSWORD_RESET",
    ACCOUNT_DELETE: "ACCOUNT_DELETE",
    ACCOUNT_VERIFY: "ACCOUNT_VERIFY",
    ANNOUNCEMENT_MODERATE: "ANNOUNCEMENT_MODERATE",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
})

export const AUDIT_TARGET_TYPES = Object.freeze({
    USER: "USER",
    ANNOUNCEMENT: "ANNOUNCEMENT",
    SUBSCRIPTION: "SUBSCRIPTION",
    REPORT: "REPORT",
})