const OTP_TYPES = Object.freeze({
    EMAIL_VERIFICATION: "EMAIL_VERIFICATION",
    PHONE_VERIFICATION: "PHONE_VERIFICATION",
    LOGIN: "LOGIN",
    PASSWORD_RESET: "PASSWORD_RESET",
    CHANGE_EMAIL: "CHANGE_EMAIL",
    CHANGE_PHONE: "CHANGE_PHONE",
});
export default OTP_TYPES